#!/usr/bin/python

import argparse

parser = argparse.ArgumentParser(
    prog='onnf-run',
    description="""
         ONNF Module Executor
    """)

parser.add_argument('--compile',
                    help='Compile model to produce a shared library file.')

parser.add_argument('module',
                    help='The ONNX module being compiled or run.')

parser.parse_args()

