#!/usr/bin/python

import argparse
from driver import *

def parse_arguments():
  parser = argparse.ArgumentParser(
    prog='onnf-run',
    description="""
         ONNX-MLIR Model Executor
    """)
  parser.add_argument('--compile',
    help='Compile model to produce a shared library file.')
  parser.add_argument('model',
    help='The ONNX model being compiled and/or run.')
  args = parser.parse_args()

  print(args.model)

if __name__ == '__main__':
  parse_arguments()
