#!/usr/bin/python

import argparse
from python.driver import *

def parse_arguments():
  parser = argparse.ArgumentParser(
    prog='onnf-run',
    description="""
         ONNX-MLIR Model Executor
    """)
  parser.add_argument('model',
    help="""The ONNX model being compiled and/or run.""")
  parser.add_argument('--mode', choices=["compile", "run", "all"]
    help="""Mode that specifies what the onnf-run tool does.
            Possible values include:
               compile : compile the input model to a shared library (only).
               run     : run the compiled model provided to the `--compiled-model` flag.
                         The origial input model has to be provided as well.
               all     : (default) compiles the input model and runs it.""")
  args = parser.parse_args()

  print(args.model)
  return args

def action_arguments(args):
  if (args.mode == "compile")


if __name__ == '__main__':
  args = parse_arguments()
